[project]
name = "nuclino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ratelimit>=2.2.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
